// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmrVj8a1HK6sR-G98Lhbpr7OXN-oDCDMU',
    appId: '1:411293256836:web:b1704ef1fdc740436dc6d1',
    messagingSenderId: '411293256836',
    projectId: 'biblio-72a1a',
    authDomain: 'biblio-72a1a.firebaseapp.com',
    storageBucket: 'biblio-72a1a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaaWVySj69FORo59S9dhCApLrlSEHrmrM',
    appId: '1:411293256836:android:65fd5894478b0e526dc6d1',
    messagingSenderId: '411293256836',
    projectId: 'biblio-72a1a',
    storageBucket: 'biblio-72a1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUHK5m6J6r72KiMSEG-75beuJYtVW0COA',
    appId: '1:411293256836:ios:6cbf9700f5773d7e6dc6d1',
    messagingSenderId: '411293256836',
    projectId: 'biblio-72a1a',
    storageBucket: 'biblio-72a1a.firebasestorage.app',
    iosBundleId: 'com.example.biblio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmrVj8a1HK6sR-G98Lhbpr7OXN-oDCDMU',
    appId: '1:411293256836:web:dcd3bd39fc30a01d6dc6d1',
    messagingSenderId: '411293256836',
    projectId: 'biblio-72a1a',
    authDomain: 'biblio-72a1a.firebaseapp.com',
    storageBucket: 'biblio-72a1a.firebasestorage.app',
  );
}
